language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - git clone https://github.com/theme-next/hexo-theme-next themes/next  # 增加 next
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "magaofei"  #修改name
  - git config user.email "mamian521@gmail.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GitHub_Blog}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - hexo  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/magaofei/magaofei.github.io.git  #设置GH_REF，注意更改yourname

